version: 2.1
orbs:
  node: circleci/node@5
  cypress: cypress-io/cypress@3
jobs:
  jest-tests:
    docker:
      - image: cimg/node:14.17 
    steps:
      - checkout 
      - node/install-packages:
          pkg-manager: npm  
      - run: npm test:jest 
  cypress-tests:
    docker:
      - image: cypress/base:14  
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Start Server
          command: npm run start:dev  
          background: true  
      - cypress/run:
          install-browsers: true  
          cypress-command: npx cypress run --browser chrome  

workflows:
  version: 2
  build-and-test:
    jobs:
      - jest-tests
      - cypress-tests:
          requires:
            - jest-tests  
