version: '2.1'
orbs:
  cypress: cypress-io/cypress@3
  node: circleci/node@5.2.0 

workflows:
  use-my-orb:
    jobs:
      - cypress/run:
          cypress-command: npx cypress run --browser chrome
          install-browsers: true
          start-command: npm run start:dev
      - jest_tests: 
          requires:
            - cypress/run 

jobs:
  jest_tests: 
    executor:
      name: node/default 
    steps:
      - checkout 
      - node/install-packages: 
          pkg-manager: npm
      - run: 
          name: Run Jest Tests
          command: npm test 
