version: 2.1
orbs:
  node: circleci/node@5
  # Use the Cypress CircleCI Orb for easy Cypress integration
  cypress: cypress-io/cypress@1.28.0
jobs:
  test-node:
    # Install node dependencies and run Jest tests
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run Jest tests
          command: npm run test -- --ci --reporters=default --reporters=jest-junit
      - store_test_results:
          path: ./test-results/
  test-e2e:
    # Run Cypress tests
    executor: cypress/base-14
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Start Server
          command: npm start
          background: true
      - cypress/run:
          # Configure according to your Cypress setup
          store_artifacts: true
          store_videos: true
workflows:
  build-and-test:
    jobs:
      - test-node
      - test-e2e:
          requires:
            - test-node
  # deploy job can be added here, following the pattern of the test jobs
