version: 2.1
orbs:
  node: circleci/node@5
  cypress: cypress-io/cypress@1.28.0

jobs:
  test-node:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run Jest tests
          command: npm run test -- --ci --reporters=default --reporters=jest-junit
      - store_test_results:
          path: ./test-results/

  test-e2e:
    executor: cypress/base-14
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Start Server
          command: npm start
          background: true
      - cypress/run:
          store_artifacts: true
          store_videos: true

workflows:
  build-and-test:
    jobs:
      - test-node
      - test-e2e:
          requires:
            - test-node

