version: 2.1
orbs:
  node: circleci/node@5
  cypress: cypress-io/cypress@3

jobs:
  test-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run Jest tests
          command: npm test -- --ci --reporters=default --reporters=jest-junit
      - store_test_results:
          path: ./test-results/

workflows:
  build-and-test:
    jobs:
      - test-node
      - cypress/run:
          requires:
            - test-node
          install-browsers: true
          start-command: 'npm run start'
          cypress-command: 'npx cypress run --browser chrome'
